apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${nfs_pvc}
  namespace: ${nfs_ns}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${size}