kind: Namespace
apiVersion: v1
metadata:
  name: volume-nfs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${nfs_pv}
  namespace: volume-nfs
  labels:
    volume.io/nfs: ${nfs_pv}
  annotations:
    original-target-ns: ${nfs_ns}
    original-target-pvc: ${nfs_pvc}
spec:
  serviceName: ${nfs_pv}
  replicas: 1
  selector:
    matchLabels:
      volume.io/nfs: ${nfs_pv}
  template:
    metadata:
      labels:
        volume.io/nfs: ${nfs_pv}
      annotations:
        original-target-ns: ${nfs_ns}
        original-target-pvc: ${nfs_pvc}
    spec:
      restartPolicy: Always
      priorityClassName: system-node-critical
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 0
      containers:
      - name: export
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: '200m'
            memory: '200Mi'
        env:
        - name: pod_uid
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: nfs_ns
          value: ${nfs_ns}
        - name: nfs_pvc
          value: ${nfs_pvc}
        # - name: export_ip
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.podIP
        - name: export_ip
          value: "0.0.0.0"
        - name: export_opt
          value: rw,sync,insecure,no_root_squash,no_subtree_check,crossmnt
        command:
        - /bin/sh
        args:
        - -axc
        - |
          # get device
          data_dev="$( df | awk '/ \/data$/ {print $1}' )"

          # get export dir
          export_dir="/var/lib/volume/nfs/${nfs_pvc}"

          if [ "${export_ip}" = "0.0.0.0" ]; then
            export_mask="0.0.0.0"
          else 
            export_mask="$( ifconfig | awk "/${export_ip}/ {print \$4}" | sed 's/Mask://' )"
          fi 

          # set env file
          printenv > ${export_dir}.env

          # start systemd to export
          nfs_service="volume-nfs@${nfs_pvc}.service"
          nsenter -t1 -m -- systemctl start "${nfs_service}"
          
          # check for success
          let timer=0
          until nsenter -t1 -m -- systemctl is-active "${nfs_service}"; do
            sleep 1
            let timer++
            [ "${timer}" -ge 10 ] && exit 1
          done 

          # show logs
          nsenter -t1 -m -- systemctl status "$nfs_service"

          # exit script 
          _exit_script() {
            nsenter -t1 -m -- systemctl stop --no-block "$nfs_service"
            exit
          }

          # main loop
          trap _exit_script SIGTERM SIGINT SIGKILL
          set +x
          while :
          do
            sleep 1
          done
        readinessProbe:
          tcpSocket:
            port: 2049
          periodSeconds: 1
        volumeMounts:
        - mountPath: /var/lib/volume/nfs
          name: nfs
          mountPropagation: Bidirectional
        - name: data
          mountPath: /var/lib/volume/nfs/${nfs_pvc}
      volumes:
      - name: nfs
        hostPath:
            path: /var/lib/volume/nfs
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        original-target-ns: ${nfs_ns}
        original-target-pvc: ${nfs_pvc} 
    spec:
      volumeMode: Filesystem
      accessModes:
      - ReadWriteMany
      storageClassName: ${data_sc}
      resources:
        requests:
          storage: ${size}
---
apiVersion: v1
kind: Service
metadata:
  name: ${nfs_pv}
  namespace: volume-nfs
  labels:
    volume.io/nfs: ${nfs_pv}
  annotations:
    original-target-ns: ${nfs_ns}
    original-target-pvc: ${nfs_pvc}
spec:
  selector:
      volume.io/nfs: ${nfs_pv}
  type: ClusterIP
  ports:
  - name: nfs
    port: 2049
  - name: nfs-udp
    port: 2049
    protocol: UDP
  - name: nlockmgr
    port: 32803
  - name: nlockmgr-udp
    port: 32803
    protocol: UDP
  - name: mountd
    port: 20048
  - name: mountd-udp
    port: 20048
    protocol: UDP
  - name: rquotad
    port: 875
  - name: rquotad-udp
    port: 875
    protocol: UDP
  - name: rpcbind
    port: 111
  - name: rpcbind-udp
    port: 111
    protocol: UDP
  - name: statd
    port: 662
  - name: statd-udp
    port: 662
    protocol: UDP

