apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 9
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      containers:
      - image: dockerhub.azk8s.cn/library/nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
        lifecycle:
            postStart:
              exec:
                command:
                - sh
                - -xc
                - | 
                  VOL="$( df -hT | grep -E Filesystem\|/var/lib/.*/nfs\|/usr/share/nginx/html )"
                  echo "<h1><pre>${VOL}</pre></h1>" > /usr/share/nginx/html/index.html
        resources:
          limits:
            cpu: '200m'
            memory: '200Mi'
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: demo-rwx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 31278
  selector:
    app: nginx
