apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${data_pvc}
  namespace: volume-nfs
spec:
  storageClassName: ${data_sc}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${size}